init_table_statements: dict = {"create_episode_wins_table": """
    CREATE TABLE IF NOT EXISTS episode_wins (
        id INTEGER PRIMARY KEY,
        season INTEGER,
        is_final_episode_of_season BOOLEAN,
        date DATE,
        is_tiebreak_episode BOOLEAN,
        twd98_video_title TEXT,
        twd98_video_link TEXT,
        nmeade_video_title TEXT,
        nmeade_video_link TEXT,
        nmeade_win BOOLEAN,
        twd98_win BOOLEAN
    );
""", "create_points_per_race_table": """
    CREATE TABLE IF NOT EXISTS points_per_race (
        id INTEGER PRIMARY KEY,
        season INTEGER,
        is_final_episode_of_season BOOLEAN,
        date DATE,
        is_tiebreak_episode BOOLEAN,
        twd98_video_title TEXT,
        twd98_video_link TEXT,
        nmeade_video_title TEXT,
        nmeade_video_link TEXT,
        race INTEGER,
        nmeade_points INTEGER,
        nmeade_track_win BOOLEAN,
        twd98_points INTEGER,
        twd98_track_win BOOLEAN
    );
""", "create_placements_table": """
    CREATE TABLE IF NOT EXISTS placements (
        id INTEGER PRIMARY KEY,
        season INTEGER,
        is_final_episode_of_season BOOLEAN,
        date DATE,
        is_tiebreak_episode BOOLEAN,
        twd98_video_title TEXT,
        twd98_video_link TEXT,
        nmeade_video_title TEXT,
        nmeade_video_link TEXT,
        race INTEGER,
        nmeade_placement INTEGER,
        twd98_placement INTEGER
    );
""", "create_items_pulled_table": """
    CREATE TABLE IF NOT EXISTS items_pulled (
        id INTEGER PRIMARY KEY,
        season INTEGER,
        is_final_episode_of_season BOOLEAN,
        date DATE,
        is_tiebreak_episode BOOLEAN,
        twd98_video_title TEXT,
        twd98_video_link TEXT,
        nmeade_video_title TEXT,
        nmeade_video_link TEXT,
        race INTEGER,
        nmeade_bananas INTEGER,
        nmeade_bloopers INTEGER,
        nmeade_bob_ombs INTEGER,
        nmeade_bullet_bills INTEGER,
        nmeade_fake_item_boxes INTEGER,
        nmeade_golden_mushrooms INTEGER,
        nmeade_green_shells INTEGER,
        nmeade_lightnings INTEGER,
        nmeade_mega_mushrooms INTEGER,
        nmeade_pows INTEGER,
        nmeade_red_shells INTEGER,
        nmeade_blue_shells INTEGER,
        nmeade_stars INTEGER,
        nmeade_thunder_clouds INTEGER,
        nmeade_triple_bananas INTEGER,
        nmeade_triple_green_shells INTEGER,
        nmeade_triple_mushrooms INTEGER,
        nmeade_triple_red_shells INTEGER,
        twd98_bananas INTEGER,
        twd98_bloopers INTEGER,
        twd98_bob_ombs INTEGER,
        twd98_bullet_bills INTEGER,
        twd98_fake_item_boxes INTEGER,
        twd98_golden_mushrooms INTEGER,
        twd98_green_shells INTEGER,
        twd98_lightnings INTEGER,
        twd98_mega_mushrooms INTEGER,
        twd98_pows INTEGER,
        twd98_red_shells INTEGER,
        twd98_blue_shells INTEGER,
        twd98_stars INTEGER,
        twd98_thunder_clouds INTEGER,
        twd98_triple_bananas INTEGER,
        twd98_triple_green_shells INTEGER,
        twd98_triple_mushrooms INTEGER,
        twd98_triple_red_shells INTEGER
    );
""", "create_itemplay_table": """
    CREATE TABLE IF NOT EXISTS itemplay (
        id INTEGER PRIMARY KEY,
        season INTEGER,
        is_final_episode_of_season BOOLEAN,
        date DATE,
        is_tiebreak_episode BOOLEAN,
        twd98_video_title TEXT,
        twd98_video_link TEXT,
        nmeade_video_title TEXT,
        nmeade_video_link TEXT,
        race INTEGER,
        nmeade_bananas INTEGER,
        nmeade_bloopers INTEGER,
        nmeade_bob_ombs INTEGER,
        nmeade_bullet_bills INTEGER,
        nmeade_fake_item_boxes INTEGER,
        nmeade_golden_mushrooms INTEGER,
        nmeade_green_shells INTEGER,
        nmeade_lightnings INTEGER,
        nmeade_mega_mushrooms INTEGER,
        nmeade_pows INTEGER,
        nmeade_red_shells INTEGER,
        nmeade_blue_shells INTEGER,
        nmeade_stars INTEGER,
        nmeade_thunder_clouds INTEGER,
        nmeade_triple_bananas INTEGER,
        nmeade_triple_green_shells INTEGER,
        nmeade_triple_mushrooms INTEGER,
        nmeade_triple_red_shells INTEGER,
        nmeade_bullet_shock_dodges INTEGER,
        nmeade_mega_mushroom_shock_dodges INTEGER,
        nmeade_scrub_shock_dodges INTEGER,
        nmeade_star_shock_dodges INTEGER,
        nmeade_star_mega_shock_dodges INTEGER,
        nmeade_crossed_line_before_shock INTEGER,
        nmeade_bullet_blue_dodges INTEGER,
        nmeade_golden_mushroom_blue_dodges INTEGER,
        nmeade_mega_mushroom_blue_dodges INTEGER,
        nmeade_mushroom_blue_dodges INTEGER,
        nmeade_triple_mushroom_blue_dodges INTEGER,
        nmeade_scrub_blue_dodges INTEGER,
        nmeade_star_blue_dodges INTEGER,
        nmeade_star_mega_blue_dodges INTEGER,
        nmeade_crossed_line_before_blue INTEGER,
        twd98_bananas INTEGER,
        twd98_bloopers INTEGER,
        twd98_bob_ombs INTEGER,
        twd98_bullet_bills INTEGER,
        twd98_fake_item_boxes INTEGER,
        twd98_golden_mushrooms INTEGER,
        twd98_green_shells INTEGER,
        twd98_lightnings INTEGER,
        twd98_mega_mushrooms INTEGER,
        twd98_pows INTEGER,
        twd98_red_shells INTEGER,
        twd98_blue_shells INTEGER,
        twd98_stars INTEGER,
        twd98_thunder_clouds INTEGER,
        twd98_triple_bananas INTEGER,
        twd98_triple_green_shells INTEGER,
        twd98_triple_mushrooms INTEGER,
        twd98_triple_red_shells INTEGER,
        twd98_bullet_shock_dodges INTEGER,
        twd98_mega_mushroom_shock_dodges INTEGER,
        twd98_scrub_shock_dodges INTEGER,
        twd98_star_shock_dodges INTEGER,
        twd98_star_mega_shock_dodges INTEGER,
        twd98_crossed_line_before_shock INTEGER,
        twd98_bullet_blue_dodges INTEGER,
        twd98_golden_mushroom_blue_dodges INTEGER,
        twd98_mega_mushroom_blue_dodges INTEGER,
        twd98_mushroom_blue_dodges INTEGER,
        twd98_triple_mushroom_blue_dodges INTEGER,
        twd98_scrub_blue_dodges INTEGER,
        twd98_star_blue_dodges INTEGER,
        twd98_star_mega_blue_dodges INTEGER,
        twd98_crossed_line_before_blue INTEGER
    );
""", "create_stage_hazards_table": """
    CREATE TABLE IF NOT EXISTS stage_hazards (
        id INTEGER PRIMARY KEY,
        season INTEGER,
        is_final_episode_of_season BOOLEAN,
        date DATE,
        is_tiebreak_episode BOOLEAN,
        twd98_video_title TEXT,
        twd98_video_link TEXT,
        nmeade_video_title TEXT,
        nmeade_video_link TEXT,
        race INTEGER,
        nmeade_fallen_off_track INTEGER,
        nmeade_fallen_into_lava INTEGER,
        nmeade_fallen_into_water INTEGER,
        nmeade_hit_cataquack INTEGER,
        nmeade_hit_cow INTEGER,
        nmeade_hit_crab INTEGER,
        nmeade_hit_goomba INTEGER,
        nmeade_hit_by_thwomp INTEGER,
        nmeade_hit_enemy_reskin INTEGER,
        twd98_fallen_off_track INTEGER,
        twd98_fallen_into_lava INTEGER,
        twd98_fallen_into_water INTEGER,
        twd98_hit_cataquack INTEGER,
        twd98_hit_cow INTEGER,
        twd98_hit_crab INTEGER,
        twd98_hit_goomba INTEGER,
        twd98_hit_by_thwomp INTEGER,
        twd98_hit_enemy_reskin INTEGER
    );
""", "create_tracks_played_table": """
    CREATE TABLE IF NOT EXISTS tracks_played (
        id INTEGER PRIMARY KEY,
        season INTEGER,
        episode INTEGER,
        is_final_episode_of_season BOOLEAN,
        date DATE,
        is_tiebreak_episode BOOLEAN,
        twd98_video_title TEXT,
        twd98_video_link TEXT,
        nmeade_video_title TEXT,
        nmeade_video_link TEXT,
        race INTEGER,
        track TEXT
    );
"""
}
